/* gen_tables.c - print the lookup tables for the RV32I solver (host only).
 *
 * Usage:
 *   gen_tables > tables.s
 *
 * Table building (quarter_turn, rank, unrank, BFS) is the same as stats.c.
 * Output tables:
 *   p_move_0 .. p_move_8   9 x 5040 halfwords   next permutation rank
 *   o_move_0 .. o_move_8   9 x 729  halfwords   next orientation rank
 *   p_distance             5040 bytes
 *   o_distance             729 bytes
 *   move_face              10 bytes (entry 9 = root, "no previous move")
 *   p_move_rows            9 words: address of p_move_m
 *   o_move_rows            9 words: address of o_move_m
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define CUBIES 7
#define NP 5040
#define NO 729
#define MOVES 9

typedef struct {
    uint8_t p[CUBIES], o[CUBIES];
} state_t;

static const uint8_t source[3][CUBIES] = {
    {1, 4, 2, 0, 3, 5, 6},
    {0, 1, 2, 4, 5, 6, 3},
    {0, 2, 5, 3, 1, 4, 6},
};
static const uint8_t twist[3][CUBIES] = {
    {1, 2, 0, 2, 1, 0, 0},
    {0, 0, 0, 1, 2, 1, 2},
    {0, 0, 0, 0, 0, 0, 0},
};

static state_t quarter_turn(state_t s, int face)
{
    state_t r;
    for (int i = 0; i < CUBIES; i++) {
        int from = source[face][i];
        r.p[i] = s.p[from];
        r.o[i] = (uint8_t) ((s.o[from] + twist[face][i]) % 3);
    }
    return r;
}

static int rank_p(const state_t *s)
{
    int p = 0;
    for (int i = 0; i < CUBIES; i++) {
        int smaller = 0;
        for (int j = i + 1; j < CUBIES; j++)
            if (s->p[j] < s->p[i])
                smaller++;
        p = p * (CUBIES - i) + smaller;
    }
    return p;
}

static int rank_o(const state_t *s)
{
    int o = 0;
    for (int i = 0; i < 6; i++)
        o = o * 3 + s->o[i];
    return o;
}

static void unrank(int p, int o, state_t *s)
{
    uint8_t avail[CUBIES] = {0, 1, 2, 3, 4, 5, 6};
    int f = 720, sum = 0;
    for (int i = 0; i < CUBIES; i++) {
        int q = p / f;
        p %= f;
        s->p[i] = avail[q];
        for (int j = q; j + 1 < CUBIES - i; j++)
            avail[j] = avail[j + 1];
        if (i < 5)
            f /= 6 - i;
    }
    for (int i = 5; i >= 0; i--) {
        s->o[i] = (uint8_t) (o % 3);
        sum += s->o[i];
        o /= 3;
    }
    s->o[6] = (uint8_t) ((3 - sum % 3) % 3);
}

static uint16_t ptab[MOVES][NP], otab[MOVES][NO];
static uint8_t pdist[NP], odist[NO];
static int queue[NP];

static void build(void)
{
    state_t s, t;
    for (int p = 0; p < NP; p++) {
        unrank(p, 0, &s);
        for (int face = 0; face < 3; face++) {
            t = s;
            for (int k = 0; k < 3; k++) {
                t = quarter_turn(t, face);
                ptab[face * 3 + k][p] = (uint16_t) rank_p(&t);
            }
        }
    }
    for (int o = 0; o < NO; o++) {
        unrank(0, o, &s);
        for (int face = 0; face < 3; face++) {
            t = s;
            for (int k = 0; k < 3; k++) {
                t = quarter_turn(t, face);
                otab[face * 3 + k][o] = (uint16_t) rank_o(&t);
            }
        }
    }
    for (int pass = 0; pass < 2; pass++) {
        int n = pass ? NO : NP, head = 0, tail = 1;
        uint8_t *dist = pass ? odist : pdist;
        memset(dist, 0xFF, n);
        dist[0] = 0;
        queue[0] = 0;
        while (head < tail) {
            int x = queue[head++];
            for (int m = 0; m < MOVES; m++) {
                int y = pass ? otab[m][x] : ptab[m][x];
                if (dist[y] == 0xFF) {
                    dist[y] = (uint8_t) (dist[x] + 1);
                    queue[tail++] = y;
                }
            }
        }
    }
}

static void print_half(const char *name, const uint16_t *v, int n)
{
    printf("%s:\n", name);
    for (int i = 0; i < n; i++)
        printf("%s%u%s", i % 16 == 0 ? "  .half " : "", v[i],
               (i % 16 == 15 || i == n - 1) ? "\n" : ", ");
}

static void print_byte(const char *name, const uint8_t *v, int n)
{
    printf("%s:\n", name);
    for (int i = 0; i < n; i++)
        printf("%s%u%s", i % 32 == 0 ? "  .byte " : "", v[i],
               (i % 32 == 31 || i == n - 1) ? "\n" : ", ");
}

int main(void)
{
    static const uint8_t move_face[MOVES + 1] = {0, 0, 0, 1, 1, 1, 2, 2, 2, 3};
    char name[32];
    build();
    /* Leading blank line: safe to append after a file with no final newline. */
    printf("\n# Generated by gen_tables.c. Do not edit by hand.\n");
    printf(".data\n");
    printf(".align 2\n");
    for (int m = 0; m < MOVES; m++) {
        sprintf(name, "p_move_%d", m);
        print_half(name, ptab[m], NP);
    }
    for (int m = 0; m < MOVES; m++) {
        sprintf(name, "o_move_%d", m);
        print_half(name, otab[m], NO);
    }
    print_byte("p_distance", pdist, NP);
    print_byte("o_distance", odist, NO);
    print_byte("move_face", move_face, MOVES + 1);
    /* Address tables last: the labels they name are already defined. */
    printf(".align 4\n");
    printf("p_move_rows:\n");
    for (int m = 0; m < MOVES; m++)
        printf("  .word p_move_%d\n", m);
    printf("o_move_rows:\n");
    for (int m = 0; m < MOVES; m++)
        printf("  .word o_move_%d\n", m);
    return 0;
}
